import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateSchema1771472373074 implements MigrationInterface {
    name = 'UpdateSchema1771472373074'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`merchant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`shop_logo_url\` \`shop_logo_url\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`shop_address\` \`shop_address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_phone\` \`contact_phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_email\` \`contact_email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_facebook\` \`contact_facebook\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_line\` \`contact_line\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_whatsapp\` \`contact_whatsapp\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`last_login\` \`last_login\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_c73a42116fe791faa952b71e9dd\``);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`shipping_address\` \`shipping_address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`shipping_provider\` \`shipping_provider\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`shipping_source\` \`shipping_source\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`shipping_destination\` \`shipping_destination\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`payment_terms\` \`payment_terms\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`contact_phone\` \`contact_phone\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`contact_facebook\` \`contact_facebook\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`contact_whatsapp\` \`contact_whatsapp\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`contact_line\` \`contact_line\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`preferred_contact_method\` \`preferred_contact_method\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`merchant_id\` \`merchant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` DROP FOREIGN KEY \`FK_4665b4d203357f4cd8d74e54b1c\``);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` DROP FOREIGN KEY \`FK_d7fd44c68cff957a9168272c745\``);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` CHANGE \`order_id\` \`order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` CHANGE \`customer_id\` \`customer_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` DROP FOREIGN KEY \`FK_b9e59e7b59ba5c0c5ab21c851f8\``);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` DROP FOREIGN KEY \`FK_a1e7e4ecb1bc8fa380194bea4db\``);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` CHANGE \`customer_order_id\` \`customer_order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` CHANGE \`order_item_id\` \`order_item_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_item_index\` \`order_item_index\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`variant\` \`variant\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`discount_type\` \`discount_type\` varchar(10) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`discount_value\` \`discount_value\` decimal(18,4) NULL`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_id\` \`order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2474866c8f8e9196ff227a7cbbd\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_574a2f0932043d4e4baf188ee05\``);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`arrived_at\` \`arrived_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`notified_at\` \`notified_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`merchant_id\` \`merchant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`created_by\` \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` DROP FOREIGN KEY \`FK_a510c6205de79e1fdecd1ce59ef\``);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` DROP FOREIGN KEY \`FK_6fb516c4659b87c8a766bc950fa\``);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` CHANGE \`merchant_id\` \`merchant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` CHANGE \`created_by\` \`created_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_bc9b909dcfd2c2b41ac18798cd6\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_b55350bc786b052e8523f313b9a\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`notification_link\` \`notification_link\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`last_retry_at\` \`last_retry_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`sent_at\` \`sent_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`error_message\` \`error_message\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`related_orders\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`related_orders\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`merchant_id\` \`merchant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`customer_id\` \`customer_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` DROP FOREIGN KEY \`FK_a8dbbf82dd0c706e67c8ec7da86\``);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` DROP FOREIGN KEY \`FK_12f222b5c376f4f681a620d77f1\``);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` CHANGE \`condition\` \`condition\` varchar(20) NULL`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` CHANGE \`arrival_id\` \`arrival_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` CHANGE \`order_item_id\` \`order_item_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_4d2d001670a67f1626fdaf4e66a\``);
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_9633581f63a15159cd19a2036c0\``);
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_64d53127da7eef1565fb166aed8\``);
        await queryRunner.query(`ALTER TABLE \`arrivals\` CHANGE \`notes\` \`notes\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` CHANGE \`order_id\` \`order_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` CHANGE \`merchant_id\` \`merchant_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` CHANGE \`recorded_by\` \`recorded_by\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_fe996f039efa99e46d75761aad0\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_c73a42116fe791faa952b71e9dd\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` ADD CONSTRAINT \`FK_4665b4d203357f4cd8d74e54b1c\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` ADD CONSTRAINT \`FK_d7fd44c68cff957a9168272c745\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` ADD CONSTRAINT \`FK_b9e59e7b59ba5c0c5ab21c851f8\` FOREIGN KEY (\`customer_order_id\`) REFERENCES \`customer_orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` ADD CONSTRAINT \`FK_a1e7e4ecb1bc8fa380194bea4db\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2474866c8f8e9196ff227a7cbbd\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_574a2f0932043d4e4baf188ee05\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` ADD CONSTRAINT \`FK_a510c6205de79e1fdecd1ce59ef\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` ADD CONSTRAINT \`FK_6fb516c4659b87c8a766bc950fa\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_bc9b909dcfd2c2b41ac18798cd6\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_b55350bc786b052e8523f313b9a\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` ADD CONSTRAINT \`FK_a8dbbf82dd0c706e67c8ec7da86\` FOREIGN KEY (\`arrival_id\`) REFERENCES \`arrivals\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` ADD CONSTRAINT \`FK_12f222b5c376f4f681a620d77f1\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_4d2d001670a67f1626fdaf4e66a\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_9633581f63a15159cd19a2036c0\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_64d53127da7eef1565fb166aed8\` FOREIGN KEY (\`recorded_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_64d53127da7eef1565fb166aed8\``);
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_9633581f63a15159cd19a2036c0\``);
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_4d2d001670a67f1626fdaf4e66a\``);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` DROP FOREIGN KEY \`FK_12f222b5c376f4f681a620d77f1\``);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` DROP FOREIGN KEY \`FK_a8dbbf82dd0c706e67c8ec7da86\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_b55350bc786b052e8523f313b9a\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_bc9b909dcfd2c2b41ac18798cd6\``);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` DROP FOREIGN KEY \`FK_6fb516c4659b87c8a766bc950fa\``);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` DROP FOREIGN KEY \`FK_a510c6205de79e1fdecd1ce59ef\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_574a2f0932043d4e4baf188ee05\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2474866c8f8e9196ff227a7cbbd\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` DROP FOREIGN KEY \`FK_a1e7e4ecb1bc8fa380194bea4db\``);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` DROP FOREIGN KEY \`FK_b9e59e7b59ba5c0c5ab21c851f8\``);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` DROP FOREIGN KEY \`FK_d7fd44c68cff957a9168272c745\``);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` DROP FOREIGN KEY \`FK_4665b4d203357f4cd8d74e54b1c\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_c73a42116fe791faa952b71e9dd\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_fe996f039efa99e46d75761aad0\``);
        await queryRunner.query(`ALTER TABLE \`arrivals\` CHANGE \`recorded_by\` \`recorded_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` CHANGE \`merchant_id\` \`merchant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` CHANGE \`order_id\` \`order_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_64d53127da7eef1565fb166aed8\` FOREIGN KEY (\`recorded_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_9633581f63a15159cd19a2036c0\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_4d2d001670a67f1626fdaf4e66a\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` CHANGE \`order_item_id\` \`order_item_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` CHANGE \`arrival_id\` \`arrival_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` CHANGE \`notes\` \`notes\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` CHANGE \`condition\` \`condition\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` ADD CONSTRAINT \`FK_12f222b5c376f4f681a620d77f1\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` ADD CONSTRAINT \`FK_a8dbbf82dd0c706e67c8ec7da86\` FOREIGN KEY (\`arrival_id\`) REFERENCES \`arrivals\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`customer_id\` \`customer_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`merchant_id\` \`merchant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP COLUMN \`related_orders\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD \`related_orders\` longtext COLLATE "utf8mb4_bin" NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`error_message\` \`error_message\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`sent_at\` \`sent_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`last_retry_at\` \`last_retry_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` CHANGE \`notification_link\` \`notification_link\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_b55350bc786b052e8523f313b9a\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_bc9b909dcfd2c2b41ac18798cd6\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` CHANGE \`created_by\` \`created_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` CHANGE \`merchant_id\` \`merchant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` ADD CONSTRAINT \`FK_6fb516c4659b87c8a766bc950fa\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` ADD CONSTRAINT \`FK_a510c6205de79e1fdecd1ce59ef\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`created_by\` \`created_by\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`merchant_id\` \`merchant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`notified_at\` \`notified_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` CHANGE \`arrived_at\` \`arrived_at\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_574a2f0932043d4e4baf188ee05\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2474866c8f8e9196ff227a7cbbd\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_id\` \`order_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`discount_value\` \`discount_value\` decimal(18,4) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`discount_type\` \`discount_type\` varchar(10) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`variant\` \`variant\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` CHANGE \`order_item_index\` \`order_item_index\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` CHANGE \`order_item_id\` \`order_item_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` CHANGE \`customer_order_id\` \`customer_order_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` ADD CONSTRAINT \`FK_a1e7e4ecb1bc8fa380194bea4db\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` ADD CONSTRAINT \`FK_b9e59e7b59ba5c0c5ab21c851f8\` FOREIGN KEY (\`customer_order_id\`) REFERENCES \`customer_orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` CHANGE \`customer_id\` \`customer_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` CHANGE \`order_id\` \`order_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` ADD CONSTRAINT \`FK_d7fd44c68cff957a9168272c745\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` ADD CONSTRAINT \`FK_4665b4d203357f4cd8d74e54b1c\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`merchant_id\` \`merchant_id\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`preferred_contact_method\` \`preferred_contact_method\` varchar(20) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`contact_line\` \`contact_line\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`contact_whatsapp\` \`contact_whatsapp\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`contact_facebook\` \`contact_facebook\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`contact_phone\` \`contact_phone\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`payment_terms\` \`payment_terms\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`shipping_destination\` \`shipping_destination\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`shipping_source\` \`shipping_source\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`shipping_provider\` \`shipping_provider\` varchar(100) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` CHANGE \`shipping_address\` \`shipping_address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_c73a42116fe791faa952b71e9dd\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` CHANGE \`last_login\` \`last_login\` timestamp NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_whatsapp\` \`contact_whatsapp\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_line\` \`contact_line\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_facebook\` \`contact_facebook\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_email\` \`contact_email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`contact_phone\` \`contact_phone\` varchar(50) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`shop_address\` \`shop_address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`merchants\` CHANGE \`shop_logo_url\` \`shop_logo_url\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`roles\` CHANGE \`description\` \`description\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`permissions\` CHANGE \`description\` \`description\` varchar(500) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`merchant_id\``);
    }

}
