import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateSchema1771737400297 implements MigrationInterface {
    name = 'UpdateSchema1771737400297'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`permissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`permission_code\` varchar(255) NOT NULL, \`description\` varchar(500) NULL, UNIQUE INDEX \`IDX_f65dbbe5dc253ff51e8a1f894d\` (\`permission_code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`role_id\` int NOT NULL, \`permission_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`role_name\` varchar(255) NOT NULL, \`description\` varchar(500) NULL, UNIQUE INDEX \`IDX_ac35f51a0f17e3e1fe12112603\` (\`role_name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`merchants\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`owner_user_id\` int NOT NULL, \`shop_name\` varchar(255) NOT NULL, \`shop_logo_url\` text NULL, \`shop_address\` text NULL, \`contact_phone\` varchar(50) NULL, \`contact_email\` varchar(255) NULL, \`contact_facebook\` text NULL, \`contact_line\` text NULL, \`contact_whatsapp\` varchar(50) NULL, \`default_currency\` varchar(10) NOT NULL DEFAULT 'THB', \`is_active\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`email\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`full_name\` varchar(255) NOT NULL, \`role_id\` int NOT NULL, \`merchant_id\` int NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`last_login\` timestamp NULL, UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_order_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`quantity\` int NOT NULL DEFAULT '0', \`selling_price_foreign\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`selling_total_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`profit_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`customer_order_id\` int NULL, \`order_item_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`order_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`order_item_index\` int NULL, \`product_name\` varchar(255) NOT NULL, \`variant\` varchar(255) NULL, \`quantity\` int NOT NULL DEFAULT '0', \`quantity_remaining\` int NOT NULL DEFAULT '0', \`purchase_currency\` varchar(10) NOT NULL, \`purchase_price\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`purchase_exchange_rate\` decimal(18,6) NOT NULL DEFAULT '1.000000', \`purchase_total_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`shipping_price\` decimal(18,4) NULL DEFAULT '0.0000', \`shipping_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_cost_before_discount_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`discount_type\` varchar(10) NULL, \`discount_value\` decimal(18,4) NULL, \`discount_amount_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`final_cost_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`final_cost_thb\` decimal(18,2) NOT NULL DEFAULT '0.00', \`selling_price_foreign\` decimal(18,4) NOT NULL DEFAULT '0.0000', \`selling_exchange_rate\` decimal(18,6) NOT NULL DEFAULT '1.000000', \`selling_total_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`profit_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`profit_thb\` decimal(18,2) NOT NULL DEFAULT '0.00', \`order_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`order_code\` varchar(100) NOT NULL, \`order_date\` date NOT NULL, \`arrival_status\` varchar(20) NOT NULL DEFAULT 'NOT_ARRIVED', \`arrived_at\` datetime NULL, \`notified_at\` datetime NULL, \`total_purchase_cost_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_shipping_cost_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_cost_before_discount_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_discount_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_final_cost_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_final_cost_thb\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_selling_amount_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_selling_amount_thb\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_profit_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_profit_thb\` decimal(18,2) NOT NULL DEFAULT '0.00', \`deposit_amount\` decimal(18,2) NOT NULL DEFAULT '0.00', \`paid_amount\` decimal(18,2) NOT NULL DEFAULT '0.00', \`remaining_amount\` decimal(18,2) NOT NULL DEFAULT '0.00', \`payment_status\` varchar(20) NOT NULL DEFAULT 'UNPAID', \`merchant_id\` int NULL, \`created_by\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customers\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`customer_name\` varchar(255) NOT NULL, \`customer_type\` varchar(20) NOT NULL, \`shipping_address\` text NULL, \`shipping_provider\` varchar(100) NULL, \`shipping_source\` varchar(255) NULL, \`shipping_destination\` varchar(255) NULL, \`payment_terms\` text NULL, \`contact_phone\` varchar(50) NULL, \`contact_facebook\` text NULL, \`contact_whatsapp\` varchar(50) NULL, \`contact_line\` text NULL, \`preferred_contact_method\` varchar(20) NULL, \`unique_token\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`merchant_id\` int NULL, UNIQUE INDEX \`IDX_832720c2a9f4c557936311f39d\` (\`unique_token\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`customer_orders\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`total_selling_amount_lak\` decimal(18,2) NOT NULL DEFAULT '0.00', \`total_paid\` decimal(18,2) NOT NULL DEFAULT '0.00', \`remaining_amount\` decimal(18,2) NOT NULL DEFAULT '0.00', \`payment_status\` varchar(20) NOT NULL DEFAULT 'UNPAID', \`order_id\` int NULL, \`customer_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`payments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`customer_order_id\` int NOT NULL, \`payment_amount\` decimal(18,2) NOT NULL, \`payment_date\` timestamp NULL, \`payment_proof_url\` text NULL, \`customer_message\` text NULL, \`status\` varchar(20) NOT NULL DEFAULT 'PENDING', \`verified_by\` int NULL, \`verified_at\` timestamp NULL, \`rejected_by\` int NULL, \`rejected_at\` timestamp NULL, \`reject_reason\` text NULL, \`notes\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`notifications\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`notification_type\` varchar(20) NOT NULL, \`channel\` varchar(20) NOT NULL, \`recipient_contact\` varchar(255) NOT NULL, \`message_content\` text NOT NULL, \`notification_link\` text NULL, \`retry_count\` int NOT NULL DEFAULT '0', \`last_retry_at\` datetime NULL, \`status\` varchar(20) NOT NULL, \`sent_at\` datetime NULL, \`error_message\` text NULL, \`related_orders\` json NULL, \`merchant_id\` int NULL, \`customer_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exchange_rates\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`base_currency\` varchar(10) NOT NULL, \`target_currency\` varchar(10) NOT NULL, \`rate_type\` varchar(10) NOT NULL, \`rate\` decimal(18,6) NOT NULL DEFAULT '0.000000', \`is_active\` tinyint NOT NULL DEFAULT 1, \`rate_date\` date NOT NULL, \`merchant_id\` int NULL, \`created_by\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`arrival_items\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`arrived_quantity\` int NOT NULL DEFAULT '0', \`condition\` varchar(20) NULL, \`notes\` text NULL, \`arrival_id\` int NULL, \`order_item_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`arrivals\` (\`id\` int NOT NULL AUTO_INCREMENT, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`arrived_date\` date NOT NULL, \`arrived_time\` time NOT NULL, \`notes\` text NULL, \`order_id\` int NULL, \`merchant_id\` int NULL, \`recorded_by\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_178199805b901ccd220ab7740ec\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_17022daf3f885f7d35423e9971e\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permissions\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`merchants\` ADD CONSTRAINT \`FK_601b7984c109a454f72d1f1029f\` FOREIGN KEY (\`owner_user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_a2cecd1a3531c0b041e29ba46e1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_fe996f039efa99e46d75761aad0\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` ADD CONSTRAINT \`FK_b9e59e7b59ba5c0c5ab21c851f8\` FOREIGN KEY (\`customer_order_id\`) REFERENCES \`customer_orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` ADD CONSTRAINT \`FK_a1e7e4ecb1bc8fa380194bea4db\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`order_items\` ADD CONSTRAINT \`FK_145532db85752b29c57d2b7b1f1\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_2474866c8f8e9196ff227a7cbbd\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD CONSTRAINT \`FK_574a2f0932043d4e4baf188ee05\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customers\` ADD CONSTRAINT \`FK_c73a42116fe791faa952b71e9dd\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` ADD CONSTRAINT \`FK_4665b4d203357f4cd8d74e54b1c\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` ADD CONSTRAINT \`FK_d7fd44c68cff957a9168272c745\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_f4390eb9dc55cbd79b606746771\` FOREIGN KEY (\`customer_order_id\`) REFERENCES \`customer_orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_fc2beb4403c1d6267b003e0889c\` FOREIGN KEY (\`verified_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`payments\` ADD CONSTRAINT \`FK_f1cf0b736bfb684c15410e1e44b\` FOREIGN KEY (\`rejected_by\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_bc9b909dcfd2c2b41ac18798cd6\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`notifications\` ADD CONSTRAINT \`FK_b55350bc786b052e8523f313b9a\` FOREIGN KEY (\`customer_id\`) REFERENCES \`customers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` ADD CONSTRAINT \`FK_a510c6205de79e1fdecd1ce59ef\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` ADD CONSTRAINT \`FK_6fb516c4659b87c8a766bc950fa\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` ADD CONSTRAINT \`FK_a8dbbf82dd0c706e67c8ec7da86\` FOREIGN KEY (\`arrival_id\`) REFERENCES \`arrivals\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` ADD CONSTRAINT \`FK_12f222b5c376f4f681a620d77f1\` FOREIGN KEY (\`order_item_id\`) REFERENCES \`order_items\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_4d2d001670a67f1626fdaf4e66a\` FOREIGN KEY (\`order_id\`) REFERENCES \`orders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_9633581f63a15159cd19a2036c0\` FOREIGN KEY (\`merchant_id\`) REFERENCES \`merchants\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`arrivals\` ADD CONSTRAINT \`FK_64d53127da7eef1565fb166aed8\` FOREIGN KEY (\`recorded_by\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_64d53127da7eef1565fb166aed8\``);
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_9633581f63a15159cd19a2036c0\``);
        await queryRunner.query(`ALTER TABLE \`arrivals\` DROP FOREIGN KEY \`FK_4d2d001670a67f1626fdaf4e66a\``);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` DROP FOREIGN KEY \`FK_12f222b5c376f4f681a620d77f1\``);
        await queryRunner.query(`ALTER TABLE \`arrival_items\` DROP FOREIGN KEY \`FK_a8dbbf82dd0c706e67c8ec7da86\``);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` DROP FOREIGN KEY \`FK_6fb516c4659b87c8a766bc950fa\``);
        await queryRunner.query(`ALTER TABLE \`exchange_rates\` DROP FOREIGN KEY \`FK_a510c6205de79e1fdecd1ce59ef\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_b55350bc786b052e8523f313b9a\``);
        await queryRunner.query(`ALTER TABLE \`notifications\` DROP FOREIGN KEY \`FK_bc9b909dcfd2c2b41ac18798cd6\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_f1cf0b736bfb684c15410e1e44b\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_fc2beb4403c1d6267b003e0889c\``);
        await queryRunner.query(`ALTER TABLE \`payments\` DROP FOREIGN KEY \`FK_f4390eb9dc55cbd79b606746771\``);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` DROP FOREIGN KEY \`FK_d7fd44c68cff957a9168272c745\``);
        await queryRunner.query(`ALTER TABLE \`customer_orders\` DROP FOREIGN KEY \`FK_4665b4d203357f4cd8d74e54b1c\``);
        await queryRunner.query(`ALTER TABLE \`customers\` DROP FOREIGN KEY \`FK_c73a42116fe791faa952b71e9dd\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_574a2f0932043d4e4baf188ee05\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP FOREIGN KEY \`FK_2474866c8f8e9196ff227a7cbbd\``);
        await queryRunner.query(`ALTER TABLE \`order_items\` DROP FOREIGN KEY \`FK_145532db85752b29c57d2b7b1f1\``);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` DROP FOREIGN KEY \`FK_a1e7e4ecb1bc8fa380194bea4db\``);
        await queryRunner.query(`ALTER TABLE \`customer_order_items\` DROP FOREIGN KEY \`FK_b9e59e7b59ba5c0c5ab21c851f8\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_fe996f039efa99e46d75761aad0\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_a2cecd1a3531c0b041e29ba46e1\``);
        await queryRunner.query(`ALTER TABLE \`merchants\` DROP FOREIGN KEY \`FK_601b7984c109a454f72d1f1029f\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_17022daf3f885f7d35423e9971e\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_178199805b901ccd220ab7740ec\``);
        await queryRunner.query(`DROP TABLE \`arrivals\``);
        await queryRunner.query(`DROP TABLE \`arrival_items\``);
        await queryRunner.query(`DROP TABLE \`exchange_rates\``);
        await queryRunner.query(`DROP TABLE \`notifications\``);
        await queryRunner.query(`DROP TABLE \`payments\``);
        await queryRunner.query(`DROP TABLE \`customer_orders\``);
        await queryRunner.query(`DROP INDEX \`IDX_832720c2a9f4c557936311f39d\` ON \`customers\``);
        await queryRunner.query(`DROP TABLE \`customers\``);
        await queryRunner.query(`DROP TABLE \`orders\``);
        await queryRunner.query(`DROP TABLE \`order_items\``);
        await queryRunner.query(`DROP TABLE \`customer_order_items\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP TABLE \`merchants\``);
        await queryRunner.query(`DROP INDEX \`IDX_ac35f51a0f17e3e1fe12112603\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP TABLE \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_f65dbbe5dc253ff51e8a1f894d\` ON \`permissions\``);
        await queryRunner.query(`DROP TABLE \`permissions\``);
    }

}
